### ISSUE TITLE
How to volunteer and submit/share generated ntlm9 tables ?

### ISSUE THREAD

**Issue by netro** [jtesta/rainbowcrackalack#17]
Hello Joe,

I would happilly volunteer a bit by generating some tables but I would like to know how could we help. I generated the first table given in your example but I guess I'm not the first one to generate this one :)

Could we setup a list of already generated tables and the ones missing for the community ?

Regards;

**Comment by jtesta** [comment]
Sorry for the late response.  Use the contact form on the website (https://www.rainbowcrackalack.com/), and send me your e-mail address, and a summary of what hardware/OS combinations you have.

I'm working now on pulling a new release together, which will generate 9-character tables much faster.  Once that's done, I'll assign a range for you to generate.  Thanks!

**Comment by jtesta** [comment]
Hi @netro.  I didn't hear back from you regarding volunteering.  If you're still interested, please reach out via that contact form with your information, and I can give you instructions for how to get started.  Thanks!
