### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by H4xl0r** [jtesta/rainbowcrackalack#18]
Its a bit unclear how to generate a full set of tables.
would be nice if you could add the commands for generating full tables or a script for 
8-8
9-9
8-9
7-9

I got a minig rig and would support the project if i would know how to generate those tables 
if i use crackalack_gen ntlm ascii-32-95 8 8 0 803000 67108864 0
It just generates one file / table ? i guess the command is wrong or some others are missing ?

would be nice if you could post those infos in more detail on the readme 

thanks

**Comment by jtesta** [comment]
The 8-character tables are already generated for NTLM, so generating those yourself doesn't make sense.  If you still really wanted to know how they are made, I suppose I could write that up.

Volunteers are currently generating 9-character tables.  To get instructions on how to help, please use the instructions on https://www.rainbowcrackalack.com/.  Thanks!

**Comment by H4xl0r** [comment]
would it be possible to use those tables / convert them ? :
http://project-rainbowcrack.com/table.htm
like ntlm_ascii-32-95#1-8 ? its rtc format  
if it is possible to use them or convert them let me know 
would be nice !

Is your tool working the same way as Rainbowcrack (speed gpu lookup etc ?)

**Comment by jtesta** [comment]
The tables from the rainbowcrack project should be fully compatible without any conversion.

As for the lookup speed of my code, it is much faster than the CPU version of the rainbowcrack software.  I didn't test Rainbowcrack's GPU-accelerated version against mine, however.

**Comment by H4xl0r** [comment]
ok understand , so the tables would be a help ? 
i have seen them as DL long time ago , maybe i find them again ;-) 

how about those : 
https://freerainbowtables.com/
they are in RTI2 format
any way to get them to work with your tool ?
i could go ahead and RTI2  to rt format them with 
https://freerainbowtables.com/rti2rto/ 
and then to rtc but i get an table already exists error.

Please help here ....im not that table guy

Suggestion:
Tool to convert between those tables rti2--rtc---rt etc .
there are many tables out there but each is different.
if there would be a way to make them compatible to all that would help a lot.
Even more then Computing those TAbles.

My goal was it to load the tables from free rainbow and convert them for your tool, but no chance :-( 
would be cool if you could have a look on those tables 👍 
mixalpha-numeric-symbol32-space#1-8 (https://freerainbowtables.com/)

rti2rt works without any other parameter:
`PS G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0> .\rti2rto.exe *.rti2
ntlm_mixalpha-numeric-all-space#1-8_0_200000x47005386_distrrtgen[p][i]_583.rti2:
Chain Position is now 47005386

ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_000.rti2:
Chain Position is now 67108864

ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_001.rti2:
Chain Position is now 67108864

ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_002.rti2:
Chain Position is now 67108864

ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_003.rti2:
Chain Position is now 67108864

ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_004.rti2:
Chain Position is now 67108864

ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_005.rti2:
Chain Position is now 67108864

fine but when using rt2rtc i got the problem 👎 : 
`PS G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0\RT> .\rt2rtc.exe G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0\RT
G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0\RT\ntlm_mixalpha-numeric-all-space#1-8_0_200000x47005386_distrrtgen[p][i]_583.rt
    minimal value of start_point_bits is 37
    minimal value of end_point_bits   is 31
    writing ntlm_mixalpha-numeric-all-space#1-8_0_200000x47005386_0.rtc...
G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0\RT\ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_000.rt
    minimal value of start_point_bits is 37
    minimal value of end_point_bits   is 31
    writing ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_0.rtc...
G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0\RT\ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_distrrtgen[p][i]_001.rt
    minimal value of start_point_bits is 37
    minimal value of end_point_bits   is 31
    ntlm_mixalpha-numeric-all-space#1-8_0_200000x67108864_0.rtc exists
PS G:\CRK\tables\RCK\ntlm_mixalpha-numeric-all-space#1-8_0\RT>`

whats wrong here ? naming ? i need help please 
`

**Comment by jtesta** [comment]
In my opinion, the tables from the Freerainbowtables project are no longer useful.  It is more effective and easier to use hashcat for those character sets and patterns.  Many other people agree, since that is why rainbow table cracking went out of style in the last 6 or 7 years.

The only case that tables are still useful are for 8 and 9 character passwords with the full US character set (or any language, really).  The [project website](https://www.rainbowcrackalack.com/) has a free torrent for the 8-character tables with the US keyboard charset.  We are currently generating 9-character tables; they should be ready in the next few months!

In theory, however, if you converted tables to RT or RTC format, you can still use them.  I'm not sure what's going wrong with your conversion, however.
