### ISSUE TITLE
Failed to open kernel.: No such file or directory

### ISSUE THREAD

**Issue by RealMasterDuke** [jtesta/rainbowcrackalack#19]
Hi,

I compiled the code for a windows machine.

I got the following error message if I want to lookup for hashes.

Binary searching will be done with 8 threads.
Loaded 18 of 18 uncracked hashes from hashes.txt.
Pre-computing hash #1: 3df1fd8f0d9c177bec1f6ff3673a26c7...

Note: optimized NTLM8 kernel will be used for precomputation.

Failed to open kernel.: No such file or directory

What files are needed here?? Thank you very much

**Comment by AlexanderKAdams** [comment]
What was your fix to this? I find I'm getting the same error.

**Comment by AlexanderKAdams** [comment]
Fix: Run it while you're in the same directory as rainbowcrackalack.
