### ISSUE TITLE
CL/cl.h missing

### ISSUE THREAD

**Issue by giovannicandotti** [jtesta/rainbowcrackalack#25]
Hi,
I've downloaded latest (1.2) version and I tried to compile on a centOS machine.
First error is about CL/cl.h missing file.
Any suggestion?
Many thanks

**Comment by giovannicandotti** [comment]
my fault, -l not configured properly

**Comment by AkechiShiro** [comment]
Can you please explain how did you solve it exactly ? @giovannicandotti

**Comment by AkechiShiro** [comment]
Figured out I needed `opencl-headers`
