### ISSUE TITLE
incorrect detection of multiple GPUs (Duplicate)

### ISSUE THREAD

**Issue by charliehk** [jtesta/rainbowcrackalack#26]
On a system with 2 GPUs, (1xGTX1070 and 1xGTX1080) I get the following when I try to run a lookup.
Two things:
1) The detection finds 2 platforms - and lists each card twice
2) After the initial pre-computing, it just goes back to the initial prompt

D:\Rainbow_Tables\RC13>.\crackalack_lookup.exe d:\Rainbow_Tables\NTLM8 3B1B47E42E0463276E3DED6CEF349F93

Rainbow Crackalack v1.3-dev
Copyright 2018-2020 Positron Security LLC <https://www.positronsecurity.com/>
Make Rainbow Tables Great Again

Operating system: Windows
Found 2 platforms.
Found 2 devices on platform #0.
Found 4 devices on platform #1.
Device #0:
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1080
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 20
        Max work group size: 1024
        Global memory size: 8589934592

Device #1:
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1070
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 15
        Max work group size: 1024
        Global memory size: 8589934592

Device #2:
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1080
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 20
        Max work group size: 1024
        Global memory size: 8589934592

Device #3:
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1070
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 15
        Max work group size: 1024
        Global memory size: 8589934592

Binary searching will be done with 24 threads.
Pre-computing hash #1: 3b1b47e42e0463276e3ded6cef349f93...

Note: optimized NTLM8 kernel will be used for precomputation.

D:\Rainbow_Tables\RC13>

**Comment by jtesta** [comment]
I added debugging code to print more information about the detected
platforms, and I guessed at a potential solution.  Could you please run
this updated build and report back its full output?  Thanks!

https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-dev.zip
https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-dev.zip.sig

**Comment by charliehk** [comment]
maybe worse? 
Here's the output
d:\Rainbow_Tables\RC13>crackalack_lookup.exe d:\Rainbow_Tables\NTLM8 3B1B47E42E0463276E3DED6CEF349F93

Rainbow Crackalack v1.3-dev
Copyright 2018-2020 Positron Security LLC <https://www.positronsecurity.com/>
Make Rainbow Tables Great Again


Operating system: Windows
Found 2 platforms.
Error while getting platform info.

**Comment by jtesta** [comment]
Oops.  Ok, try this build:

https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-2.zip
https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-2.zip.sig


On Tue, 2021-02-23 at 17:41 -0800, charliehk wrote:
> maybe worse?
> Here's the output
> d:\Rainbow_Tables\RC13>crackalack_lookup.exe d:\Rainbow_Tables\NTLM8
> 3B1B47E42E0463276E3DED6CEF349F93
> 
> Rainbow Crackalack v1.3-dev
> Copyright 2018-2020 Positron Security LLC 
> https://www.positronsecurity.com/
> Make Rainbow Tables Great Again
> 
> Operating system: Windows
> Found 2 platforms.
> Error while getting platform info.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by charliehk** [comment]
d:\Rainbow_Tables\RC13>.\crackalack_lookup.exe d:\Rainbow_Tables\NTLM8 3B1B47E42E0463276E3DED6CEF349F93

Rainbow Crackalack v1.3-platformfix-2
Copyright 2018-2021 Positron Security LLC <https://www.positronsecurity.com/>
Make Rainbow Tables Great Again


Operating system: Windows
Found 2 platforms.
Error while getting platform info: -30

**Comment by jtesta** [comment]
The reason I can't test these changes myself is because my equipment
doesn't appear as two separate platforms.  I've never seen a system do
this except yours.  Since I can't test my changes, I have to keep
guessing.  I appreciate the help with this!

Ok, here's another build.  This time it'll continue if any errors are
encountered:

https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-3.zip
https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-3.zip.sig

**Comment by charliehk** [comment]
> The reason I can't test these changes myself is because my equipment doesn't appear as two separate platforms. I've never seen a system do this except yours. Since I can't test my changes, I have to keep guessing. I appreciate the help with this! Ok, here's another build. This time it'll continue if any errors are encountered: https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-3.zip https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-3.zip.sig

Yeah no worries. thanks for your help. I don't understand it either. The only thing that I can think of, is that it was mixed GPU. Even during install of the nvidia drivers, I had to reboot in between. If you get to frustrated, don't worry about it. This is really only a temporary platform, until I get some 3080s - but the stock is so short, I've been waiting since Sept for them.

**Comment by charliehk** [comment]
d:\Rainbow_Tables\RC13>.\crackalack_lookup.exe d:\Rainbow_Tables\NTLM8 3B1B47E42E0463276E3DED6CEF349F93

Rainbow Crackalack v1.3-platformfix-3
Copyright 2018-2021 Positron Security LLC <https://www.positronsecurity.com/>
Make Rainbow Tables Great Again


Operating system: Windows
Found 2 platforms.
Platform #0:
        Vendor: NVIDIA Corporation
        Name: NVIDIA CUDA
        Version: OpenCL 1.2 CUDA 11.2.135
        Profile: FULL_PROFILE
        Extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid

Platform #1:
        Vendor: NVIDIA Corporation
        Name: NVIDIA CUDA
        Version: OpenCL 1.2 CUDA 11.2.135
        Profile: FULL_PROFILE
        Extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid

Found 2 devices on platform #0.
Found 2 devices on platform #1.
Device #0:
        ID: 00000000007B6A10
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1080
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 20
        Max work group size: 1024
        Global memory size: 8589934592

Device #1:
        ID: 00000000007B6290
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1070
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 15
        Max work group size: 1024
        Global memory size: 8589934592

Device #2:
        ID: 00000000007B6470
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1080
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 20
        Max work group size: 1024
        Global memory size: 8589934592

Device #3:
        ID: 00000000007B6560
        Vendor: NVIDIA Corporation
        Name: GeForce GTX 1070
        Version: OpenCL 1.2 CUDA
        Driver: 461.40
        Max compute units: 15
        Max work group size: 1024
        Global memory size: 8589934592

Binary searching will be done with 24 threads.
Pre-computing hash #1: 3b1b47e42e0463276e3ded6cef349f93...

Note: optimized NTLM8 kernel will be used for precomputation.
d:\Rainbow_Tables\RC13>

An FYI on things I've done for troubleshooting.
1) Clean install option - during nvidia driver install
2) Removed hidden devices 

I might try Display Driver Uninstalled (DDU) next.

**Comment by charliehk** [comment]
FYI - I just tried DDU - and the install drivers (no physx/HD audio driver) after, and I got the same results. 
But I tried hashcat, and it's detecting multiple platforms as well - and ignores the duplicates.
I'm going to just try a refresh on the OS, and see if that fixes things.

**Comment by charliehk** [comment]
I'm closing this issue, as it seems that it is my computer that is the problem

**Comment by jtesta** [comment]
What made you think this was a local problem?  Is it no longer
reporting multiple platforms?

If you do still see multiple platforms, I made a new build for you to
try:

https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-4.zip
https://www.rainbowcrackalack.com/Rainbow_Crackalack_Win64_v1.3-platformfix-4.zip.sig

Try running it with `crackalack_lookup.exe d:\Rainbow_Tables\NTLM8
3B1B47E42E0463276E3DED6CEF349F93 -disable-platform 0` and see if that
works.  If not, try with '-disable-platform 1'.  Either way, please
copy/paste all the output.

**Comment by charliehk** [comment]
I'm pretty sure it's a local issue - because:
a) Hashcat detecting duplicates as well
b) Issue isn't there when I remove one of the cards
c) issue is still there when I did a full refresh of Windows

So I think it might be a driver thing with multiple cards, but they don't match. Because I basically have to go through the Nvidia driver install twice.

I already took out a card. I will test this the next time I'm in the office though.

**Comment by jtesta** [comment]
I'm thinking it could be a driver bug.  The new '-disable-platform'
option might let you get around it, however.

And the fact that hashcat works automatically but my program crashes is
interesting...

I look forward to hearing how '-disable-platform' works for you!
