### ISSUE TITLE
Need benchmark mode for bounties

### ISSUE THREAD

**Issue by llamasoft** [jtesta/rainbowcrackalack#4]
If there's going to be a bounty for OpenCL/FPGA performance increases, there should be a functioning benchmark mode that doesn't also involve writing result data to disk.
https://github.com/jtesta/rainbowcrackalack/blob/cbf745288d75b55f0a5c3ec57b3a818f77e94b1b/crackalack_gen.c#L528-L532

This may be something I'm willing to help with.  What exactly was the issue leading to the benchmark mode being disabled?

**Comment by jtesta** [comment]
I disabled it a long time ago, but from what I recall, I kept breaking it while adding other features.  It was too much work (and no benefit) to keep it maintained that early in the development process.

If you'd like to get it working again, I'd happily accept a PR for it!
